-- CreateEnum
CREATE TYPE "language" AS ENUM ('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'ITALIAN', 'PORTUGUESE', 'RUSSIAN', 'CHINESE', 'JAPANESE', 'ARABIC', 'HINDI', 'KOREAN', 'TURKISH', 'VIETNAMESE', 'THAI', 'INDONESIAN', 'MALAY', 'URDU', 'BENGALI', 'PERSIAN', 'DUTCH', 'POLISH', 'SWEDISH', 'FINNISH', 'DANISH', 'NORWEGIAN', 'CZECH', 'ROMANIAN', 'HUNGARIAN', 'GREEK', 'BULGARIAN', 'SERBIAN', 'CROATIAN', 'SLOVENIAN', 'MACEDONIAN', 'SLOVAK', 'MALTESE', 'CATALAN', 'ICELANDIC', 'WELSH', 'BASQUE', 'GALICIAN', 'SCOTS_GAELIC', 'MALAGASY', 'MAORI', 'TAMIL', 'TELUGU', 'KANNADA', 'MALAYALAM', 'SINHALESE', 'BURMESE', 'KHMER', 'LAO', 'TIBETAN', 'MONGOLIAN', 'DZONGKHA', 'GEORGIAN', 'ARMENIAN', 'AZERBAIJANI', 'YIDDISH', 'KURDISH', 'HEBREW', 'UIGHUR', 'URUMCHI', 'KAZAKH', 'TATAR', 'UZBEK', 'TURKMEN', 'KYRGYZ', 'TAJIK', 'PUNJABI', 'GUJARATI', 'ORIYA', 'ASSAMESE', 'MARATHI', 'SANSKRIT', 'MANDARIN', 'CANTONESE', 'HAKKA', 'XHOSA', 'ZULU', 'AFRIKAANS', 'SWAHILI', 'SOMALI', 'LUXEMBOURGISH', 'LINGALA', 'KINYARWANDA', 'TSWANA', 'NYANJA', 'KIRUNDI', 'VIET');

-- AlterTable
ALTER TABLE "Lawyer" ADD COLUMN     "language" "language" NOT NULL DEFAULT 'ENGLISH';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "language" "language" NOT NULL DEFAULT 'ENGLISH';
